batch_size: 4
iters: 40000

train_dataset:
  type: Dataset #因为是自定义数据集，所以需要选这个，数据读取格式，只要按照上面的方法来制作数据集
  dataset_root: data/five_data
  train_path: data/five_data/train.txt
  num_classes: 4  #类别个数，背景也算一类
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/five_data
  val_path: data/five_data/train.txt
  num_classes: 4  #类别个数，背景也算一类
  transforms:
    
    - type: Padding
      target_size: [1024, 1024]
   
    - type: Normalize
  mode: val


optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1,1]

model:
  type: OCRNet
  backbone:
    type: HRNet_W48
    
  backbone_indices: [0]
