batch_size: 4
iters: 860000

train_dataset:
  type: Dataset
  dataset_root: data/DeepGlobe
  train_path: data/DeepGlobe/train.txt
  num_classes: 4  #类别个数，背景也算一类
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [ 512, 512 ]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize
  mode: train

test_config:
  aug_eval: True
  scales: 1.0

val_dataset:
  type: Dataset
  dataset_root: data/DeepGlobe
  val_path: data/DeepGlobe/val.txt
  num_classes: 4  #类别个数，背景也算一类
  transforms:
    - type: Normalize
  mode: val


optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 5.0e-4

lr_scheduler:
  type: CosineAnnealingWarmRestarts
  learning_rate: 0.0005
  T_0: 10000

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 65000   # batch_size * 1024 * 512 // 16
    - type: OhemCrossEntropyLoss
      min_kept: 65000
    - type: OhemCrossEntropyLoss
      min_kept: 65000
  coef: [1, 1, 1]


model:
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]
